Document: soothsayer
Title: Debian soothsayer Manual
Author: <insert document author here>
Abstract: This manual describes what soothsayer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/soothsayer/soothsayer.sgml.gz

Format: postscript
Files: /usr/share/doc/soothsayer/soothsayer.ps.gz

Format: text
Files: /usr/share/doc/soothsayer/soothsayer.text.gz

Format: HTML
Index: /usr/share/doc/soothsayer/html/index.html
Files: /usr/share/doc/soothsayer/html/*.html

  
