#!/bin/sh

##########
#  Presage, an extensible predictive text entry system
#  ------------------------------------------------------
#
#  Copyright (C) 2008  Matteo Vescovi <matteo.vescovi@yahoo.co.uk>
#  Copyright (C) 2008  Tiziano D'Albis
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# this scripts converts all the texts in the corpus from xml to txt.
# the actual conversion is performed by the script 'xml2txt'

find Texts/A -regex .*xml -exec xml2txt {}   \;
find Texts/B -regex .*xml -exec xml2txt {}   \;
find Texts/C -regex .*xml -exec xml2txt {}   \;
find Texts/D -regex .*xml -exec xml2txt {}   \;
find Texts/E -regex .*xml -exec xml2txt {}   \;
find Texts/F -regex .*xml -exec xml2txt {}   \;
find Texts/G -regex .*xml -exec xml2txt {}   \;
find Texts/H -regex .*xml -exec xml2txt {}   \;
find Texts/J -regex .*xml -exec xml2txt {}   \;
find Texts/K -regex .*xml -exec xml2txt {}   \;