#!/bin/bash

##########
#  Presage, an extensible predictive text entry system
#  ------------------------------------------------------
#
#  Copyright (C) 2008  Matteo Vescovi <matteo.vescovi@yahoo.co.uk>
#  Copyright (C) 2008  Tiziano D'Albis
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

if [ $# -lt 2 ]
then
    echo "Usage: $0 input output"
    exit 1
fi

INPUT=$1
OUTPUT=$2

cat $INPUT | text2wfreq | wfreq2vocab -top 20000 > $OUTPUT.vocab
cat $INPUT | text2idngram -n 3 -vocab $OUTPUT.vocab -temp . > $OUTPUT.idngram
idngram2lm -idngram $OUTPUT.idngram -vocab $OUTPUT.vocab -arpa $OUTPUT.arpa 

